# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

require 'json'
podfile_properties = begin
  JSON.parse(File.read(File.join(__dir__, 'Podfile.properties.json')))
rescue
  {}
end

ENV['RCT_NEW_ARCH_ENABLED'] = podfile_properties['newArchEnabled'] == 'false' ? '0' : '1'

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'SavingsGoalWallet' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => podfile_properties['hermesEnabled'] != 'false',
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
    # Xcode 26 Clang rejects fmt 11 consteval. The header redefines FMT_USE_CONSTEVAL,
    # so a -D flag is not enough; wrap detection and force 0.
    fmt_base = File.join(installer.sandbox.root, 'fmt/include/fmt/base.h')
    if File.exist?(fmt_base)
      contents = File.read(fmt_base)
      unless contents.include?('SGW_FMT_USE_CONSTEVAL_GUARD')
        contents.sub!(
          "// Detect consteval, C++20 constexpr extensions and std::is_constant_evaluated.\n#if !defined(__cpp_lib_is_constant_evaluated)",
          "// Detect consteval, C++20 constexpr extensions and std::is_constant_evaluated.\n#ifndef FMT_USE_CONSTEVAL // SGW_FMT_USE_CONSTEVAL_GUARD\n#if !defined(__cpp_lib_is_constant_evaluated)"
        )
        contents.sub!(
          "#  define FMT_USE_CONSTEVAL 0\n#endif\n#if FMT_USE_CONSTEVAL\n#  define FMT_CONSTEVAL consteval",
          "#  define FMT_USE_CONSTEVAL 0\n#endif\n#endif\n#if FMT_USE_CONSTEVAL\n#  define FMT_CONSTEVAL consteval"
        )
        File.chmod(0o644, fmt_base)
        File.write(fmt_base, contents)
      end
    end
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |build_config|
        cxx_flags = build_config.build_settings['OTHER_CPLUSPLUSFLAGS'] || ['$(inherited)']
        cxx_flags = [cxx_flags] if cxx_flags.is_a?(String)
        unless cxx_flags.include?('-DFMT_USE_CONSTEVAL=0')
          cxx_flags << '-DFMT_USE_CONSTEVAL=0'
        end
        build_config.build_settings['OTHER_CPLUSPLUSFLAGS'] = cxx_flags
      end
    end
  end
end
